title: Artyom Kalmykov
email: artyom.kalm@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://artyomkalm.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  artyomkalm

# Build settings
markdown: kramdown
